### ISSUE TITLE
Conky unable to locate weather-1.png in .cache

### ISSUE THREAD

**Issue by DavidMetcalfe** [zenzire/conkyrc#4]
Can't locate weather-1.png in code, and it does not seem to be placed in .cache as the code expects. Ideas?

**Comment by derrekbertrand** [comment]
The problem here is that you don't have curl installed. Installing curl will fix the issue.

Debian/Ubuntu/Mint:

    sudo apt-get install curl

**Comment by Fugor** [comment]
Well I have curl installed and I get the same messages..
